### ISSUE TITLE
Layout design

### ISSUE THREAD

**Issue by MoyasiGinko** [MoyasiGinko/Portfolio-Site#9]
- Background images compatibility with responsive design
- Grid implementation
- Reference design [Visit here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34-848&t=cRL3QtqucdEhjtlw-0)

**Comment by MasterLeiva** [comment]
Hi @MoyasiGinko,

🎉 Great project! You're project looks great, but there are some suggestions that can improve your design.

<img src="https://media.giphy.com/media/9JtCCeSviDLFNhYir6/giphy.gif?cid=ecf05e47oaisbsyh6xreezie30r77ec9daf5rqmvoyefd7o6&rid=giphy.gif&ct=g" />

## Highlights
- Accessible ✔️ 
- Clean Code ✔️ 
- Grid and Flexbox Layout ✔️ 

## Required Changes 🛠
- [x] I suggest removing the break tag `<br>` from your "About me" title, as this will make your design look more like Figma's. 👌🏼
- [x] I kindly advise that you add margin-bottom of 20px to the "textarea" tag on your form, so that the spacing can match the other inputs.
